### ISSUE TITLE
Does not work under firefox :-)

### ISSUE THREAD

**Issue by ergo** [PolymerLabs/indie-catalog#2]
https://polymerlabs.github.io/indie-catalog/

Throws TypeError: a.__shady is undefined

**Comment by notwaldorf** [comment]
Seems to be a polyfill bug: https://github.com/webcomponents/webcomponentsjs/issues/811

**Comment by notwaldorf** [comment]
Updated deps and looks fine locally. Will redeploy!

**Comment by ergo** [comment]
Confirmed fixed :-) TY
